name: pypi

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Publish to Pypi
      env:
        TWINE_REPOSITORY: pypi
        TWINE_NON_INTERACTIVE: true
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
