name: pyright

on:
  schedule:
    - cron: 0 9 * * 4
  push:
    branches: [main]
  pull_request:

jobs:
  on-ubuntu-latest-py37:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up npm
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Check types with Pyright
      run: |
        npx pyright
